# Generated by Django 4.2.5 on 2023-11-24 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
    ]
