# Generated by Django 4.2.5 on 2023-11-14 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STATUS_NEW", "новый"),
                            ("STATUS_DELIVERY", "в доставке"),
                            ("STATUS_FINISHED", "завершен"),
                            ("STATUS_CANCELED", "отменен"),
                        ],
                        default="STATUS_NEW",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Покупка",
                "verbose_name_plural": "Покупки",
            },
        ),
        migrations.CreateModel(
            name="OrderRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Покупка",
                "verbose_name_plural": "Покупки",
            },
        ),
    ]
