# Generated by Django 4.2.5 on 2023-11-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrow",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="order_rows", to="products.item"
            ),
        ),
        migrations.AddField(
            model_name="orderrow",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="orders", through="orders.OrderRow", to="products.item"
            ),
        ),
    ]
