# Generated by Django 4.2.5 on 2023-11-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("новый", "новый"),
                    ("в доставке", "в доставке"),
                    ("завершен", "завершен"),
                    ("отменен", "отменен"),
                ],
                default="новый",
                max_length=30,
            ),
        ),
    ]
