version: "3.3"

networks:
  private:
  
volumes:
  pg_data:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    networks:
      - private
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: antuanuran/diplom:latest
    restart: always
    env_file:
      - .env    
    networks:
      - private
    depends_on:
      - db
    volumes:
      - ./static:/app/static

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - private
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/static
    ports:
      - 80:80

    



