# Generated by Django 4.2.5 on 2023-11-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("basket", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketrow",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="basket_rows", to="products.item"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="baskets", through="basket.BasketRow", to="products.item"
            ),
        ),
    ]
